#!/usr/bin/env bash
#a manage_my_process Bash script

start () {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop () {
    pkill -f "./manage_my_process"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}
